# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8b0dbcbdd6fd109311ad095953532230"
application_url = "https://advertising-sink-foo-resistant.trycloudflare.com"
embedded = true
name = "HNUK Specs Management - Jeff"
handle = "hnuk-specs-management-jeff"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_users"

[auth]
redirect_urls = [
  "https://advertising-sink-foo-resistant.trycloudflare.com/auth/callback",
  "https://advertising-sink-foo-resistant.trycloudflare.com/auth/shopify/callback",
  "https://advertising-sink-foo-resistant.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

[build]
automatically_update_urls_on_dev = true
