# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "52e70aff3c37f2e75a4c4ba27d90c0f1"
name = "HNUK Name - DEV"
application_url = "https://app-name-hnni-uat-dev.au.azure.hndigital.net"
handle = "hnuk-name-dev"
embedded = true

[access_scopes]
scopes = "read_users"

[auth]
redirect_urls = [
	"https://app-name-hnni-uat-dev.au.azure.hndigital.net/auth/callback",
	"https://app-name-hnni-uat-dev.au.azure.hndigital.net/auth/shopify/callback",
	"https://app-name-hnni-uat-dev.au.azure.hndigital.net/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

[pos]
embedded = false

[build]