# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cb345dcc3c85a2114f4bac13054bc468"
name = "HNIE Name - UAT"
application_url = "https://app-name-hnie-uat.au.azure.hndigital.net"
handle = "hnie-name-uat"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
scopes = "read_users"

[auth]
redirect_urls = [
	"https://app-name-hnie-uat.au.azure.hndigital.net/auth/callback",
	"https://app-name-hnie-uat.au.azure.hndigital.net/auth/shopify/callback",
	"https://app-name-hnie-uat.au.azure.hndigital.net/api/auth/callback"
]

[pos]
embedded = false

[build]